### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by pschmitt** [newreleasesio/cli-go#1]
Hi, I wanted to write a quick and dirty script to add all the starred repos to my account (and sync deletions automatically).

I've been hit with rate-limiting really fast though. What are the actual limits?

**Comment by janos** [comment]
Hi, Philip. The limit is 1000 requests per hour for GET requests, but POST and DELETE requests are counted 10 times more. More about it can be found in https://newreleases.io/api/v1 section 5. Rate Limiting. This means that only 100 project attempts can be made per hour. Attempts that fail because of bad request 400 are counted the same as ok 200. I believe that this is the case, as per quick look in API usage logs.

**Comment by pschmitt** [comment]
Thanks for the info. My spaghetti script was actually hitting the API with the wrong discord channel ID (stupid me thought that I needed to provide the actual discord channel ID, not newreleases.io channel IDs).

Is there any gentle way to sync periodically the subscribed repos with the repos I starred on GitHub? If not I guess I'll just bite the bullet and implement my script in a more gentle (and therefore slow) way. I happen to have 1000+ starred repositories...

**Comment by janos** [comment]
I'm glad that it was helpful.

Currently there is no such feature to subscribe to github stars, but it is a nice idea. API should be there to solve use cases that we did not think of, like this one.

Since you have a larger number of projects to track, more than a limit per account, please write a few words on https://newreleases.io/contact for us to raise the limit of projects and to identify your account correctly. The limit exists to avoid abuses, only.

**Comment by pschmitt** [comment]
Cool, hey. I just dropped a few words on your contact page. Thanks for the help!

**Comment by pschmitt** [comment]
Quick follow-up

I released my script: https://github.com/pschmitt/nrgh-sync

**Comment by janos** [comment]
Thanks for sharing Philipp, it is great. :)
